gym/urls.py
from django.contrib import admin
from django.urls import include, path
from  django.conf import settings
from django.conf.urls.static import static
from payments.views import  PaymentPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitness.urls')),
    path('gym_admin/', include('gym_admin.urls')),
    path('gym_user/', include('gym_user.urls')),
    path('gym_trainee/', include('gym_trainee.urls')),
    path('payments/', include('payments.urls')),
   
    
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gym_admin/urls.py
from django.urls import include, path
from . import views
from xml.dom.minidom import Document
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
app_name = "gym_admin"
urlpatterns = [
    path('', views.adminhome, name='adminhome'),
    path('traineeregistration', views.traineeregistration, name='traineeregistration'),
    path('plann', views.plann, name='plann'),
    path('viewalluserregistration/<int:id>', views.viewalluserregistration, name='viewalluserregistration'),
    path('viewregister', views.viewregister, name='viewregister'),
    path('addclass', views.addclass, name='addclass'),
    path('viewcreatedplan', views.viewcreatedplan, name='viewcreatedplan'),
    path('addworkoutsummary/<int:id>', views.addworkoutsummary, name='addworkoutsummary'),
    path('addmachinery', views.addmachinery, name='addmachinery'),
    path('viewfeedback', views.viewfeedback, name='viewfeedback'),
    path('viewtrainee', views.viewtrainee, name='viewtrainee'),
    path('traineeviewall', views.traineeviewall, name='traineeviewall'),
    path('addhealthstatus', views.addhealthstatus, name='addhealthstatus'),
    path('viewallcreatedplans/<int:id>', views.viewallcreatedplans, name='viewallcreatedplans'),
    path('adminviewmachinery', views.adminviewmachinery, name='adminviewmachinery'),
    
] 

gym_trainee/urls.py
from django.urls import path
from . import views

app_name = "gym_trainee"
urlpatterns = [
    path('', views.traineehome, name='traineehome'),
    path('traineeform/<int:id>', views.traineeform, name='traineeform'),
     path('uploadhealthstatus/<int:id>', views.uploadhealthstatus, name='uploadhealthstatus'),
     path('uploadroutine', views.uploadroutine, name='uploadroutine'),
     path('traineeviewuserregister', views.traineeviewuserregister, name='traineeviewuserregister'),
     path('markattendance', views.markattendance, name='markattendance'),
     path('dietplan/<int:id>', views.dietplan, name='dietplan'),
]

gym_trainee/models.py
from django.db import models
from fitness.models import Register

# Create your models here.


class UserHealthStatus(models.Model):
    user_fk = models.ForeignKey(Register, on_delete=models.CASCADE)
    user_healthstatus = models.CharField(max_length=100, default="")
    uploading_date = models.DateField()

class UserAttendance(models.Model):
    user_fk = models.ForeignKey(Register, on_delete=models.CASCADE)
    attendance = models.CharField(max_length=10, default="absent")
    timestamp = models.DateTimeField(auto_now_add=True)

class UploadRoutine(models.Model):
    excercise_type = models.CharField(max_length=50, default="")
    day_1 = models.CharField(max_length=50, default="")
    day_2 = models.CharField(max_length=50, default="")
    day_3 = models.CharField(max_length=50, default="")
    day_4 = models.CharField(max_length=50, default="")
    day_5 = models.CharField(max_length=50, default="")
    day_6 = models.CharField(max_length=50, default="")
    day_7 = models.CharField(max_length=50, default="")
    def __str__(self):
        return self.name

class FitnessDietPlan(models.Model):
    user_fk = models.ForeignKey(Register, on_delete=models.CASCADE)
    food_to_add = models.JSONField(blank=True, default=list)
    food_to_avoid =  models.JSONField(blank=True, default=list)
    pre_workout_food =  models.JSONField(blank=True, default=list)
    post_workout_food =  models.JSONField(blank=True, default=list)

    class Meta():
        db_table = 'fitnessdietplan'

gym_trainee/forms.py
from django import forms
from .models import UploadRoutine

class RoutineSelectionForm(forms.Form):
    routine = forms.ModelChoiceField(queryset=UploadRoutine.objects.all())

gym_trainee/views.py
from django.shortcuts import render,redirect
from gym_admin.models import TraineeRegister
from gym_trainee.models import UserHealthStatus, UploadRoutine
from fitness.models import Register
from .models import *
import datetime

# Create your views here.
def traineehome(request):
    return render(request, 'traineehome.html')
def traineeform(request, id):
    
          
     return render(request, 'traineeform.html')
def uploadhealthstatus(request, id):
    user_status = Register.objects.get(id=id)
    if request.method == 'POST':
        user_health_status = request.POST['healthstatus']
        status_uploading_date = request.POST['healthstatusdate']
        check_status = UserHealthStatus.objects.filter(user_fk=id).first()
        if check_status:
            UserHealthStatus.objects.filter(user_fk=id).update(user_healthstatus=user_health_status,uploading_date=status_uploading_date)
        else:
            register = UserHealthStatus(user_fk=user_status, user_healthstatus=user_health_status, uploading_date=status_uploading_date)
            register.save()
            print('saved')

        return redirect('gym_trainee:traineehome')
    return render(request, 'uploadhealthstatus.html', {"user_status":user_status})
def markattendance(request):
    user_detail = Register.objects.all()
    now = datetime.datetime.now()
    midnight = now.replace(hour=0, minute=0,second=0, microsecond=0)
    if now > midnight and not request.user.is_anonymous:
        user_detail.update(attendance=None)
    if request.method == 'POST':
        
        for user in user_detail:
            attendance = request.POST.get("attendance_"+str(user.id), 'absent')
            if user.attendance == "present" or user.attendance == "absent":
                UserAttendance.objects.filter(user_fk=user).update(attendance=attendance)
                Register.objects.filter(id=user.id).update(attendance=attendance)
            else:
                mark_attendance = UserAttendance(user_fk=user, attendance=attendance)
                user.attendance = attendance
                user.save()
                mark_attendance.save()
        return redirect("gym_trainee:markattendance")
        # else:
        #     message = "Attendance can only be marked until 12 AM"
        #     return render(request,'markattendance.html', {"user_detail":user_detail, "message":message})
        # for  user in user_detail:
        #     user.attendance  = UserAttendance.objects.filter(user_fk=user, timestamp__gte=midnight)
    return render(request,'markattendance.html', {"user_detail":user_detail})
        

def uploadroutine(request):
    msg = 'msg'
    if request.method == 'POST':
        type_of_excercise = request.POST['ex_type']
        day_0ne = request.POST['day1']
        day_two = request.POST['day2']
        day_three = request.POST['day3']
        day_four = request.POST['day4']
        day_five = request.POST['day5']
        day_six = request.POST['day6']
        day_sev = request.POST['day7']
        excercise_type_exist =UploadRoutine.objects.filter(excercise_type=type_of_excercise) 
        if excercise_type_exist:
            msg = 'this type is already added'
        else:
            register=UploadRoutine(excercise_type=type_of_excercise, day_1=day_0ne, day_2=day_two, day_3=day_three, day_4=day_four, day_6=day_six, day_7=day_sev)
            register.save()
            return redirect('gym_trainee:uploadroutine')

   

    return render(request,'uploadroutine.html', {"msg":msg})
def traineeviewuserregister(request):
    traineeviewuser = Register.objects.all()
    return render(request, 'traineeviewuserregister.html', {"traineeviewuser":traineeviewuser})
def dietplan(request, id):
    if request.method == 'POST':
        user_fk = Register.objects.get(id=id)
        print("workint 1")
        foodto_add = request.POST.getlist('required_food[]')
        foodto_avoid = request.POST.getlist('notrequired_food[]')
        preworkout_food = request.POST.getlist('pre_workout_food[]')
        postworkout_food =request.POST.getlist('Post_workout_food[]')
        diet_check = FitnessDietPlan.objects.filter(user_fk=id).first()
        user_fk = Register.objects.get(id=id)

        #foodtoadd
        all_foodtoadd = []
        foodtoadd_dict = {}
        required_food = []
        print(foodto_add)
        for foodtoadd in foodto_add:
            foodtoadd_data = {}
            quantity_key = foodtoadd + '_type'
            quantity = request.POST[quantity_key]
            print(foodtoadd, quantity )
            foodtoadd_data["foodtoadd"] = foodtoadd
            foodtoadd_data["quantity"] = quantity
            required_food.append(foodtoadd_data)

        foodtoadd_dict["foodtoadd"] = required_food
        all_foodtoadd.append(foodtoadd_dict)

        #foodtoavoid
        all_foodtoavoid = []
        foodtoavoid_dict = {}
        notrequired_food = []
        for foodtoavoid in foodto_avoid:
            foodtoavoid_data ={}
            quantity_key = foodtoavoid + '_type'
            quantity = request.POST[quantity_key]
            print(foodtoavoid, quantity )
            foodtoavoid_data["foodtoavoid"] = foodtoavoid
            foodtoavoid_data["quantity"] = quantity
            notrequired_food.append(foodtoavoid_data)

        foodtoavoid_dict["foodtoavoid"] = notrequired_food
        all_foodtoavoid.append(foodtoavoid_dict)
        
        #preworkoutfood
        all_preworkoutfood = []
        preworkout_dict = {}
        pre_workout_food = []
        for preworkoutfood in preworkout_food:
            preworkout_data ={}
            quantity_key = preworkoutfood + '_type'
            quantity = request.POST[quantity_key]
            print(preworkoutfood, quantity )
            preworkout_data["preworkoutfood"] = preworkoutfood
            preworkout_data["quantity"] = quantity
            notrequired_food.append(preworkout_data)

        preworkout_dict["preworkoutfood"] = pre_workout_food
        all_preworkoutfood.append(preworkout_dict)

        #postworkoutfood
        all_postworkoutfood = []
        postworkout_dict = {}
        post_workout_food = []
        for postworkoutfood in postworkout_food:
            postworkout_data = {}
            quantity_key = postworkoutfood + '_type'
            quantity = request.POST[quantity_key]
            print(postworkout_data, quantity )
            postworkout_data["postworkoutfood"] = postworkout_data
            postworkout_data["quantity"] = quantity
            post_workout_food.append(postworkout_data)

        postworkout_dict["postworkoutfood"] = post_workout_food
        all_postworkoutfood.append(postworkout_dict)
        
        if diet_check:
            FitnessDietPlan.objects.filter(user_fk=id).update(food_to_add=foodtoadd_dict, food_to_avoid=foodtoavoid_dict, pre_workout_food=preworkout_dict, post_workout_food=postworkout_dict)
            return redirect("gym_trainee:traineehome")
        else:
            register = FitnessDietPlan(user_fk=user_fk, food_to_add=foodtoadd_dict, food_to_avoid=foodtoavoid_dict, pre_workout_food=preworkout_dict, post_workout_food=postworkout_dict)
            register.save()
            return redirect("gym_trainee:traineehome")

    return render(request, 'dietplan.html')

gym_trainee/templates/markattendance.html
{% extends 'trainee_base.html'%}

{% block body %}
<div class=" vh-100 attendance">
    <div class="container pt-5">
        <form method="POST">
          {% csrf_token %}
      <div class="card  mx-auto card-registration my-2 card w-auto">


        <div class="card-body p-md-8 text-black bg-white">
      <h2 class="text-uppercase text-center fw-bold text-dark report_font pb-4 " >Mark Attendance</h2>
          {% if message %}
          <p>{{message}}</p>
          {% endif %}
      <table class="table table-white">
        <thead>
          <tr class="text-black">
            <th scope="col">#</th>
            <th scope="col" class="">MEMBER NAME</th>
            <th scope="col">ATTENDANCE</th>
          </tr>
        </thead>
        <tbody>                 
            {% for data in user_detail %}
         <tr>
            <td>{{forloop.counter}}</td>
           <td>{{data.register_fname}} . {{data.register_lname}}</td>
           <td>
           
          

                <div class="form-check form-check-inline mb-0 me-4">
                  <input class="form-check-input" type="radio" name="attendance_{{forloop.counter}}" id="" value="present" 
                  {% if data.attendance == 'present' %} checked {% endif %}/>
                  <label class="form-check-label text-black" for="femaleGender">Present</label>
                </div>

                <div class="form-check form-check-inline mb-0 me-4">
                  <input class="form-check-input" type="radio" name="attendance_{{forloop.counter}}" id="" value="absent" {% if data.attendance == 'absent' %} checked {% endif %} />
                  <label class="form-check-label text-black" for="maleGender">Absent</label>
                </div>

                
            </td>
           
  
          </tr>
          {% endfor %}
          
  
        </tbody>
        
      </table>
      <button class="btn btn-sm" type="submit">Post attendance</button>
  
        </div>
      </div>
      </form>

    </div>
  </div>
{% endblock %}

gym_trainee/templates/trainee_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block head %}
    {% endblock %}
    

    <title>GYM Trainee</title>
   
    

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
        <script src="https://unpkg.com/bootstrap-multiselect@0.9.13/dist/js/bootstrap-multiselect.js"></script>
<link href="https://unpkg.com/bootstrap-multiselect@0.9.13/dist/css/bootstrap-multiselect.css" rel="stylesheet"/>
<script src="https://code.jquery.com/jquery-3.7.0.js"
        integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"> <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Custom styles for this template-->
    <link href="{% static 'css/vewplan.css'%}" rel="stylesheet" />
  <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
  
  
    <link href="{% static 'css/registration.css'%}" rel="stylesheet" />
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
   

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav  sidebar sidebar-dark accordion w-25 " id="accordionSidebar" style="background-color: #2e2759; width: max-content;">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'gym_admin:adminhome' %}">
                <div class="sidebar-brand-icon">
                    <!-- <i class="fas fa-laugh-wink"></i> --><img src="{%static 'assets/img/culogo3.png'%}" width="50" height="50" class="d-inline-block align-top " alt="">
                    
                </div>
                <div class="sidebar-brand-text mx-2 "><h6>GYM Trainee</h6><figcaption></figcaption></div>
                
               
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'gym_trainee:traineehome' %}">
                  <i class="fas fa-fw fa-tachometer-alt"></i>
                  <span>My profile</span></a>
          </li>
           <!-- Divider -->
           <hr class="sidebar-divider">


            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gym_trainee:traineeviewuserregister' %}">
                    <i class="fas fa-solid fa-users"></i>
                    <span>View MemberList</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'gym_trainee:markattendance' %}">
                    <i class="fas fa-solid fa-user-check"></i>
                    <span>Mark attendance</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gym_trainee:uploadroutine' %}">
                    <i class="fas fa-solid fa-list"></i>
                    <span>workout Routine</span></a>
            </li>

            

            
           

           
            

           
            
           





         
           
           


           
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>


        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>


                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                
                                <span class="mr-2 d-none d-lg-inline text-white small text-wrap" ><button class="btn btn-primary">LOGOUT</button></span>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                              
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    {% block body %} {% endblock %}
                </div>
            </div>

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

gym_trainee/templates/traineehome.html
{% extends 'trainee_base.html' %}
{% block body %}
{% endblock %}

gym_trainee/templates/traineeviewuserregister.html
{% extends 'trainee_base.html' %}
{% block body %}

<div class=" vh-100 ">
    <div class="container pt-5">
      <div class="card  mx-auto card-registration my-2 card w-auto">


        <div class="card-body p-md-8 text-black bg-white">
      <h2 class="text-uppercase text-center fw-bold text-dark report_font pb-4 " >MEMBER LIST</h2>
  
  
      <table class="table table-white">
        <thead>
          <tr class="text-black">
            <th scope="col">#</th>
            <th scope="col" class="">MEMBER NAME</th>
            <th scope="col">EMAIL</th>
            <th scope="col">PHONE</th>
            <th scope="col">ACTION</th>
          </tr>
        </thead>
        <tbody>
          {% for data in traineeviewuser %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{data.register_fname}} . {{data.register_lname}}</td>
            <td>{{data.register_email}}</td>
            <td>{{data.register_phone}}</td>
            
            <td><div class="pb-2"><a class="btn text-white " style="background-color: rgb(5, 5, 208);" href="{% url 'gym_trainee:uploadhealthstatus' data.id %}">Add HealthStatus</a></div>
              <a class="btn text-white " style="background-color: rgb(5, 5, 208);" href="{% url 'gym_trainee:dietplan' data.id %}">Add diet-plan</a></td>
  
          </tr>
          {% endfor %}
  
  
        </tbody>
      </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

gym_trainee/templates/uploadhealthstatus.html
{% extends 'trainee_base.html'%}
{% block body %}
   
        <section class="h-100">
          <form action="" name="registerform" method="POST" onsubmit="">
            {% csrf_token %}
          <div class="container py-5 h-30">
            <div class="row d-flex justify-content-center align-items-center h-30">
              <div class="col">
               
                <div class="card  mx-auto card-registration my-2 card w-50">
                  
                    
                      <div class="card-body p-md-8 text-black">
                      
                        
                        <h4 class="mb-5 text-uppercase text-center ">Upload Health Status</h4>
                       
        
                        <div class="row">
                          <div class="col-md-12 mb-4">
                            <div class="form-outline">
                              <label class="form-label text-black" for="form3">Member Name</label>
                              <input type="text" name="regname1" id="id"  class="form-control form-control-sm  reginput" value="{{user_status.register_fname}} . {{user_status.register_lname}}" disabled/>
                            
                            </div>
                          </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 mb-4">
                              <div class="form-outline">
                                <label class="form-label text-black" for="form3">Height</label>
                                <input type="text" name="regname1" id="id"  class="form-control form-control-sm  reginput" value="{{user_status.user_height}}" disabled />
                              </div>
                            </div>
                            <div class="col-md-6 mb-4">
                              <div class="form-outline">
                                <label class="form-label text-black" for="form3Example1n">Weight</label>
                                <input type="text"  name= "regname2" id="id" class="form-control form-control-sm reginput" value="{{user_status.user_weight}}" disabled/>
                               
                              </div>
                            </div>
                          </div>
                       
                          <div class="form-outline mb-2">
                            <label class="form-label text-black" for="form3Example8">BloodGroup</label>
                            <input type="text" name="regaddress" id="id" class="form-control form-control-sm reginput" value="{{user_status.blood_group}}" disabled/>
                            
                          </div>
                          <div class="form-outline mb-2">
                            <label class="form-label text-black" for="form3Example8">Date</label>
                            <input type="date" name="healthstatusdate" id="form7" class="form-control form-control-sm reginput" placeholder="Enter health status" />
                            
                          </div>
                          <div class="form-outline mb-2">
                            <label class="form-label text-black" for="form3Example8">Attendance</label>
                            <!-- <select name="" id="" disabled="disabled">
                              <option value="">04-08-33 <input type="checkbox" disabled="disabled"checked></option>
                            </select> -->
                            <input type="text" name="healthattendance" id="form7" class="form-control form-control-sm reginput"  />
                            
                          </div>
                          <div class="form-outline mb-2">
                            <label class="form-label text-black" for="form3Example8">Status</label>
                            <input type="text" name="healthstatus" id="form7" class="form-control form-control-sm reginput" placeholder="Enter health status" />
                            
                          </div>
                          
                          <div class="d-flex justify-content-between pt-3">
                            <button type="reset" class="btn btn-light btn-sm">Reset all</button>
                            <button type="submit" class="btn btn-primary btn-sm ms-2">Upload</button>
                          </div>
                      </div>
                </div>
              </div>
            </div>
          </div>
          </form>
        </section>
    
{% endblock %}



  