gym/urls.py
from django.contrib import admin
from django.urls import include, path
from  django.conf import settings
from django.conf.urls.static import static
from payments.views import  PaymentPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitness.urls')),
    path('gym_admin/', include('gym_admin.urls')),
    path('gym_user/', include('gym_user.urls')),
    path('gym_trainee/', include('gym_trainee.urls')),
    path('payments/', include('payments.urls')),
   
    
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gym_admin/urls.py
from django.urls import include, path
from . import views
from xml.dom.minidom import Document
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
app_name = "gym_admin"
urlpatterns = [
    path('', views.adminhome, name='adminhome'),
    path('traineeregistration', views.traineeregistration, name='traineeregistration'),
    path('plann', views.plann, name='plann'),
    path('viewalluserregistration/<int:id>', views.viewalluserregistration, name='viewalluserregistration'),
    path('viewregister', views.viewregister, name='viewregister'),
    path('addclass', views.addclass, name='addclass'),
    path('viewcreatedplan', views.viewcreatedplan, name='viewcreatedplan'),
    path('addworkoutsummary/<int:id>', views.addworkoutsummary, name='addworkoutsummary'),
    path('addmachinery', views.addmachinery, name='addmachinery'),
    path('viewfeedback', views.viewfeedback, name='viewfeedback'),
    path('viewtrainee', views.viewtrainee, name='viewtrainee'),
    path('traineeviewall', views.traineeviewall, name='traineeviewall'),
    path('addhealthstatus', views.addhealthstatus, name='addhealthstatus'),
    path('viewallcreatedplans/<int:id>', views.viewallcreatedplans, name='viewallcreatedplans'),
    path('adminviewmachinery', views.adminviewmachinery, name='adminviewmachinery'),
    
] 

gym_user/urls.py
from django.urls import include, path
from . import views
app_name = "gym_user"
urlpatterns = [
    path('', views.userhome, name='userhome'),
    
    path('feedback', views.feedback, name='feedback'),
    path('viewroutine', views.viewroutine, name='viewroutine'),
    path('viewdiet', views.viewdiet, name='viewdiet'),
    path('viewplan', views.viewplan, name='viewplan'),
    path('viewmachinery', views.viewmachinery, name='viewmachinery'),
    path('workoutsummary/<int:id>', views.workoutsummary, name='workoutsummary'),
    path('healthstatus', views.healthstatus, name='healthstatus'),
    path('routineplan', views.routineplan, name='routineplan'),
    
]

gym_user/models.py
from django.db import models

# Create your models here.
class EnterFeedback(models.Model):
    f_name = models.CharField(max_length=25)
    f_mail = models.CharField(max_length=25)
    f_feedback = models.CharField(max_length=100)

gym_user/views.py
from django.shortcuts import render, redirect
from gym_admin.models import CreatePlan, AddMachineryDetails 
from .models import EnterFeedback
from gym_trainee.models import *
import datetime
from django.utils import timezone

# Create your views here.
def userhome(request):
    user_id = request.session['user_id']
    user = Register.objects.get(id=user_id)
    return render(request, 'userhome.html', {"user":user})

    
def feedback(request):
      if request.method == 'POST':
        feed_name = request.POST['feedname']
        feed_mail = request.POST['feedmail']
        feed_text = request.POST['feedtext']

        register = EnterFeedback(f_name=feed_name, f_mail=feed_mail, f_feedback=feed_text)
        register.save()
        print("saved")
        return redirect('gym_user:feedback')

      return render(request,'feedback.html/')
def viewroutine(request):
    return render(request,'viewroutine.html/')
def viewdiet(request):
    user_id = request.session['user_id']
    dietplan = UserHealthStatus.objects.filter(user_fk=user_id).first()

    return render(request,'viewdiet.html/', {"dietplan":dietplan})
def viewplan(request):
    userplan = CreatePlan.objects.all()
    return render(request,'viewplan.html/', {"userplan":userplan},)
def viewmachinery(request):
    machineries = AddMachineryDetails.objects.all()

    return render(request,'viewmachinery.html/', {"machineries":machineries})
def workoutsummary(request, id):
    planuser = CreatePlan.objects.get(id=id)
    return render(request,'workoutsummary.html/', {"planuser":planuser})

def healthstatus(request):
    user_id = request.session['user_id']
    users = Register.objects.get(id=user_id)
    health_status = UserHealthStatus.objects.filter(user_fk=user_id).first()
    today = timezone.now()
    print("today: ",today)
    one_week_ago = today - datetime.timedelta(days=7)
    print("one_week_ago: ",one_week_ago)
    print("user: ",users.time_stamp)
    total_days_to_work = (today - users.time_stamp).days // 7 * 6
    print("total_days_to_work: ",total_days_to_work)
    present_days = UserAttendance.objects.filter(
        user_fk=users,
        timestamp__gte=one_week_ago,
        timestamp__lt=today,
        attendance="present"
    ).count()
    return render(request, 'healthstatus.html', {"health_status":health_status, "users_name":users, "total_days_to_work":total_days_to_work, "present_days": present_days})
def routineplan(request):
    exc_type = UploadRoutine.objects.all()

    return render(request,'routineplan.html/', {"exc_type":exc_type})



       

gym_user/templates/feedback.html
{% extends 'userbase.html' %}
{% block body %}



<section class="vh-100" >
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-auto">
            <div class="card h-auto w-50" style="border-radius: 0.25rem;">


                <div class="card-body p-4 p-lg-5 text-black">

                    <form>

                        <div class="d-flex align-items-center mb-3 pb-1">
                            
                            <span class="h1 fw-bold mb-0 " >feedback</span>
                        </div>

                        <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">let us know!
                        </h5>

                        <div class="form-outline mb-4">
                            <label class="form-label" for="form2Example17">feedback</label>
                            <input type="email" id="form2Example17" class="form-control form-control-lg" placeholder="write something...."/>
                            
                        </div>

                       

                        <div class="pt-1 mb-4">
                            <button class="btn btn-lg btn-block text-white" type="submit" style="background-color: rgb(19, 95, 246);">submit</button>
                        </div>

                       
                       
                       
                    </form>

                </div>
            </div>

        </div>
    </div>

</section>

<!-- <form role="form"  method="POST">
        {% csrf_token %}
    <div class="container">
        
                    <div class=" p1 p-4">
                        

                            <div class="row mb-4">
                                <div class="col-md-12 ps-0">
        
                            <h2 class="justify-content-center"> LET US KNOW!</h2>
                                </div>
                                </div>


                        <div class="row mb-4">
                          <div class="col-md-12 ps-0 justify-content-center">
                            <input type="text" class="form-control" name="feedname" placeholder="Name">
                          </div>
                          </div>
                          <div class="row mb-4">
                            <div class="col-md-12 ps-0 justify-content-center">
                              <input type="email" class="form-control" name="feedmail" placeholder="Email">
                            </div>
                            </div>
                <div class="row mb-4">
                    <div class="col-md-12 ps-0 justify-content-center">
                        
                        <textarea class="form-control py-2 w-100" id="text" name="feedtext" placeholder="message"></textarea>
                    </div>
                </div>


                <div class="row ">
                    <div class="col-md-12 py-4 mb-2 justify-content-center">
                        <button type="submit" class="btn btn-danger btn-lg btn-block " value="submit">Submit feedback</button>
                    </div>
                </div>
                        
                    </div>
                </div>
                </div>
            </div>
    </form>-->
{% endblock %}

gym_user/templates/healthstatus.html
{% extends 'userbase.html' %}
{% block body%}
<section class="h-100">
  <form method="POST" class="">
    {% csrf_token %}
    <div class="container  pt-5 h-30">
      <div class="row d-flex justify-content-center align-items-center h-30">
        <div class="col">
          <div class="card  mx-auto card-registration my-2 card w-100">


            <div class="card-body p-md-8 text-black">
              <h4 class="mb-5 text-uppercase text-center">Health Report</h4>
              
                <div class="row">
                  <div class="col-sm-3">
                <label class="form-label text-black" for="form9">Date:{{health_status.uploading_date}}</label>
                  </div>
                  <div class="col-sm-4">
                    <div class="form-outline mb-2 pb-5">
                <input type="text"  class="form-control form-control-sm  " style="border: none; outline: none;"
                   />
                    </div>
                
              </div>
              </div>
              <div class="row">
                <div class="col-sm-4 mb-4">
                    <label class="form-label text-black pt-2" >Member name:   {{users_name.register_fname}}.{{users_name.register_lname}}</label>
                </div>
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <input type="text" name="" value=" "
                      class="form-control form-control-sm  " style="border: none; outline: none;" />
                  </div>
                  </div>
                </div>
                
              <div class="row">
                <div class="col-md-3 mb-4"> 
                    <label class="form-label text-black pt-1" for="form3">Previous weight: {{users_name.user_weight}}</label>
                </div>
                <div class="col-md-3 mb-4">
                  <div class="form-outline">
                    <input type="text" name="regname1" id="firstname_id" class="form-control form-control-sm  "
                       style="border-bottom: 2px;border: 0px; outline: none;" value=" "/>
                </div>
                  </div>
                  <div class="col-md-3 mb-4"> 
                    <label class="form-label text-black" for="form3">Current weight:</label>
                </div>

                <div class="col-md-3 mb-4">
                  <div class="form-outline">
                    <input type="text" name="regname2" id="lastname_id" class="form-control form-control-sm" style="outline: none; border: none;" />
                </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3 mb-4"> 
                    <label class="form-label text-black" for="form3">Total Hours to work:{{total_days_to_work}}</label>
                </div>
                <div class="col-md-3 mb-4">
                  <div class="form-outline">
                    <input type="text"  class="form-control form-control-sm  " style="border: 0px; outline: none;"/>
                </div>
                  </div>
                  <div class="col-md-3 mb-4"> 
                    <label class="form-label text-black" for="form3">hours worked:{{present_days}}</label>
                </div>

                <div class="col-md-3 mb-4">
                  <div class="form-outline">
                    <input type="text"  class="form-control form-control-sm " style="border: 0px; outline: none;"value="{{present_days.present_days}}"/>
                </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3 mb-4"> 
                    <label class="form-label text-black" for="">BloodGroup: {{users_name.blood_group}}</label>
                </div>
                <div class="col-md-3 mb-4">
                  <div class="form-outline">
                    <input type="text"  class="form-control form-control-sm " style="border: 0px; outline: none;"/>
                </div>
                </div>



   <!-- <h2 class="display-5">Hello, {{users_name.register_fname}}</h2>-->
    <p class="lead">Status: {{health_status.user_healthstatus}} uploaded on  {{health_status.uploading_date}} </p>
    <hr class="my-4">
    <p> </p>
    <p class="lead">
       <!--<a class="btn " href=""></a>-->
    </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
</section>


{% endblock %}
<!--<h3>{{health_status.user_healthstatus}}</h3>
    <h3>{{health_status.uploading_date}}</h3>-->

gym_user/templates/routineplan.html
{% extends 'userbase.html'%}


{% block body %}
<!-- products/templates/products/product_details.html -->
<!DOCTYPE html>



<section class="h-100">
    <form  method="POST">
        {% csrf_token %}
        
        <div class="container  pt-5 h-30">
            <div class="row d-flex justify-content-center align-items-center h-30">
                <div class="col">
                    <div class="card  mx-auto card-registration my-2 card w-50">


                        <div class="card-body p-md-8 text-black">
                            <h4 class="mb-5  text-start text-dark">Select excercise type:</h4>
                            
                            <div class="row">
                                <div class="col-md-6 mb-4 mt-4">
                                    
                                    <select class="select  ps-3 mb-0 text-dark w-100 h-100 reginput" name="regcity"
                                        id="city_id">
                                        {% for data in exc_type %}
                                        <option value="{{forloop.counter}}" class="text-dark">{{data.excercise_type}}</option>
                                        {% endfor %}
                                    </select>


                                </div>
                                <div class="col-md-6 mb-4 mt-4 pt-1">
                                    
                <button type="submit" class="btn  btn-sm ms-2 text-white" id="submit_btn" style="background-color: blue;">View routine</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </form>
</section>
{% endblock %}


<!-- search.html -->
<!--<!DOCTYPE html>
<html>
<head>
    <title>Data Search</title>
</head>
<body>
    <h1>Data Search</h1>
    <form method="post" action="">
        {% csrf_token %}
        <label for="dropdown1">Dropdown 1:</label>
        <select name="dropdown1" id="dropdown1">
            <option value="value1">Value 1</option>
            <option value="value2">Value 2</option>
            Add more options as needed 
        </select>
        <br>
        <label for="dropdown2">Dropdown 2:</label>
        <select name="dropdown2" id="dropdown2">
            <option value="value3">Value 3</option>
            <option value="value4">Value 4</option>
             Add more options as needed -->
<!-- </select>
        <br>
        <button type="submit">Search</button>
    </form>
</body>
</html>-->

gym_user/templates/userbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block head %}
    {% endblock %}
    

    <title>GYM User</title>
    

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/vewplan.css'%}" rel="stylesheet" />
  <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
  
  
    <link href="{% static 'css/registration.css'%}" rel="stylesheet" />
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
   

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav  sidebar sidebar-dark accordion" id="accordionSidebar" style="background-color: #2e2759;">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center h-auto" href="{% url 'gym_admin:adminhome' %}">
                <div class="sidebar-brand-icon ">
                    <img src="{%static 'assets/img/OIP.jpg'%}" alt="avatar"
                          class="rounded-circle img-fluid" style="width: 150px;">
                    <!-- <i class="fas fa-laugh-wink"></i> -->
                    <figcaption class="figure-caption text-center">Athulya AV</figcaption>
                </div>
                
                <div class="sidebar-brand-text mx-3"></div>
                
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'gym_user:userhome' %}">
                  <i class="fas fa-fw fas fa-id-card"></i>
                  <span>My Profile</span></a>
          </li>
           <!-- Divider -->
           <hr class="sidebar-divider">


            
           <!-- <li class="nav-item">
                <a class="nav-link" href="{% url 'gym_user:viewplan' %}">
                    <i class="fas fa-solid fa-user"></i>
                    <span>Membership plan</span></a>
            </li>-->

            <li class="nav-item">
              <a class="nav-link" href="{% url 'gym_user:viewdiet' %}">
                  <i class="fas fa-solid fa-list"></i>
                  <span>Diet PLan</span></a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'gym_user:healthstatus' %}">
                <i class="fas fa-solid fa-heart"></i>
                <span>My health Status</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'gym_user:routineplan' %}">
              <i class="fas fa-solid fa-running"></i>
              <span>workout routine</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'gym_user:feedback' %}">
            <i class="fas fa-solid fa-comments"></i>
            <span>Feedback</span></a>
    </li>

            
           

           
            

           
            
           





         
           
           


           
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>


        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>


                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               
                                <span class="mr-2 d-none d-lg-inline text-white small text-wrap" ><button class="btn btn-primary">LOGOUT</button></span>
                                
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                              
                                <a class="btn " href="">close</a>
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400 "></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    {% block body %} {% endblock %}
                </div>
            </div>

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

gym_user/templates/userhome.html
{% extends 'userbase.html' %}



{% block body %}
<section>
  <div class="container py-5">
    <div class="row">
      <div class="card mb-4">
        <div class="card-body">
          
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Full Name</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{user.register_fname}} . {{user.register_lname}}</p>
            </div>
          </div>
        <hr>

          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Email</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{user.register_email}}</p>
            </div>
          </div>
          <hr>

          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Phone</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{user.register_phone}}</p>
            </div>
          </div>
          <hr>

          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">UserName</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{user.register_username}}</p>
            </div>
          </div>
          <hr>

          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Address</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{user.register_address}}-{{user.register_pin}}, {{user.register_city}},{{user.register_state}}</p>
            </div>
          </div>
          <hr>
          
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Gender</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{user.register_gender}}</p>
            </div>
          </div>
          <hr>

          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">BloodGroup</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">A+ve</p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Height</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{user.user_height}}</p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Weight</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{user.user_weight}}</p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">Selected Plan</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{user.register_selectplan}}</p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-9">
              <button class="btn" style="background-color: rgb(6, 6, 150);"><i class="fas fa-solid  fa-user-edit"></i>Update Profile</button>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>
        <!--<h3>{{user.register_fname}}</h3>
        <h3>{{user.register_lname}}</h3>-->
        {% endblock %}
        <!-- <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">WELCOME</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">Thanks for joining our fitness center! we can't wait to share the best deals and advice with you.</p>
                        <a class="btn btn-primary btn-xl" href="#about">Leave?</a>
                    </div>
                </div>
            </div>
        </header>-->
        <!-- About-->
        <!--  <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">We've got what you need!</h2>
                        <hr class="divider divider-light" />
                        <p class="text-white-75 mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!</p>
                        <a class="btn btn-light btn-xl" href="#services">LogOut</a>
                    </div>
                </div>
            </div>
        </section>-->

gym_user/templates/viewmachinery.html
{% extends 'fitness/base.html'%}

{% load static %}

{% block body%}


    
    <div class="text-center pt-5">
        <header>OUR MACHINERIES</header>
    </div>
    {% for data in machineries %}
    <div class="card mb-3 mx-auto text-dark bg-white  w-100 h-100" style="border: none;">
        <div class="row g-0 boxoutline">
          <div class="col-md-4">
           
            <img src="{{data.machinery_image.url}}" class=" card-img-top img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title text-center"> {{data.machinery_name}} </h5>
              <p class="card-text text-center">{{data.machinery_function}}</p>
              
              
            </div>
          </div>
        </div>
        
      </div>
      {% endfor %}
    
    
    
    



{% endblock %}

gym_user/templates/viewplan.html
{% extends 'userbase.html'%}
{% load static %}
{% block body %}


    <div class=" vh-100 attendance">
        <div class="container pt-5">
          <div class="mx-auto mt-5">
           <h2 class="text-uppercase text-center fw-bold text-light report_font pb-6 bg-dark">Membership Plan Details</h2>

      
    <table class="table">
        <thead>
          <tr class="table-light">
            <th scope="col">#</th>
            <th scope="col"> PLAN NAME</th>
            <th scope="col">DESCRIPTION</th>
            <th scope="col">VALIDITY</th>
            <th scope="col">AMOUNT</th>
            <th scope="col">ACTION</th>
          </tr>
        </thead>
        <tbody>
          {% for data in userplan%}
          <tr class="table-light">
            
            <th scope="row">{{forloop.counter}}</th>
            
            <td>{{data.plan_name}}</td>
            <td>{{data.plan_description}}</td>
            <td>{{data.plan_validity}}</td>
            <td>{{data.plan_amount}}</td>
            <td><a class="btn btn-dark" href="{% url 'gym_user:workoutsummary' data.id %}">WORKOUT SUMMARY</a></td>
            
            
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
      </div>
      </div>
    </div>
      
{% endblock %}