gym/urls.py
from django.contrib import admin
from django.urls import include, path
from  django.conf import settings
from django.conf.urls.static import static
from payments.views import  PaymentPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitness.urls')),
    path('gym_admin/', include('gym_admin.urls')),
    path('gym_user/', include('gym_user.urls')),
    path('gym_trainee/', include('gym_trainee.urls')),
    path('payments/', include('payments.urls')),
   
    
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gym_admin/urls.py
from django.urls import include, path
from . import views
from xml.dom.minidom import Document
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
app_name = "gym_admin"
urlpatterns = [
    path('', views.adminhome, name='adminhome'),
    path('traineeregistration', views.traineeregistration, name='traineeregistration'),
    path('plann', views.plann, name='plann'),
    path('viewalluserregistration/<int:id>', views.viewalluserregistration, name='viewalluserregistration'),
    path('viewregister', views.viewregister, name='viewregister'),
    path('addclass', views.addclass, name='addclass'),
    path('viewcreatedplan', views.viewcreatedplan, name='viewcreatedplan'),
    path('addworkoutsummary/<int:id>', views.addworkoutsummary, name='addworkoutsummary'),
    path('addmachinery', views.addmachinery, name='addmachinery'),
    path('viewfeedback', views.viewfeedback, name='viewfeedback'),
    path('viewtrainee', views.viewtrainee, name='viewtrainee'),
    path('traineeviewall', views.traineeviewall, name='traineeviewall'),
    path('addhealthstatus', views.addhealthstatus, name='addhealthstatus'),
    path('viewallcreatedplans/<int:id>', views.viewallcreatedplans, name='viewallcreatedplans'),
    path('adminviewmachinery', views.adminviewmachinery, name='adminviewmachinery'),
    
] 

gym_admin/models.py
from django.db import models

# Create your models here.
class CreatePlan(models.Model):
    plan_name = models.CharField(max_length=100)
    plan_description = models.TextField()
    plan_validity = models.CharField(max_length=100)
    plan_amount = models.BigIntegerField()
    workout_type = models.CharField(max_length=50)
    days_per_week = models.CharField(max_length=25)
    time_per_workout = models.CharField(max_length=25)
    equipment_required = models.CharField(max_length=50)
    target_gender = models.CharField(max_length=7)

class TraineeRegister(models.Model):
    trainee_firstname = models.CharField(max_length=50, default="")
    trainee_lastname = models.CharField(max_length=20, default="")
    trainee_username = models.CharField(max_length=20, default="")
    trainee_mail = models.CharField(max_length=50, default="")
    trainne_password = models.CharField(max_length=8, default="")
    trainee_address = models.CharField(max_length=100, default="")
    trainee_number = models.BigIntegerField()
    trainee_gender = models.CharField(max_length=10, default="")


    

class AddMachineryDetails(models.Model):
    machinery_name = models.CharField(max_length=50)
    machinery_function = models.CharField(max_length=100)
    machinery_image = models.ImageField(upload_to ='machineryimage')





    

gym_admin/views.py
from django.shortcuts import render, redirect
from fitness.models import *
from . models import CreatePlan, TraineeRegister, AddMachineryDetails
from gym_user.models import EnterFeedback
from django.core.mail import send_mail
from django.conf import settings


# Create your views here.
def adminhome(request):
    return render(request,'gym_admin/adminhome.html')
def traineeregistration(request):
    msg = ''
    if request.method == 'POST':
     t_fname = request.POST['tfname']
     t_lname = request.POST['tlname']
     t_username = request.POST['tusername']
     t_password = request.POST['tpassword']
     t_mail = request.POST['temail']
     t_gender =request.POST['tgender']
     t_address = request.POST['taddress']
     t_phone = request.POST['tphone']
     user_exist = TraineeRegister.objects.filter(trainne_password = t_password)
     username_exist = TraineeRegister.objects.filter(trainee_username = t_username)
     email_exist = TraineeRegister.objects.filter(trainee_mail= t_mail)
     if user_exist:
         msg = 'password already exist'
     elif username_exist:
         msg = 'username already exist'
     elif email_exist:
         msg = 'email already exist'
         
     else:
         register= TraineeRegister(trainee_firstname=t_fname, trainee_lastname=t_lname, trainne_password=t_password, trainee_username=t_username, trainee_mail=t_mail, trainee_gender=t_gender, trainee_address= t_address, trainee_number=t_phone)
         subject = "Fitness Club Trainee Registration"
         message = f"Hi {t_fname}, \n\n your Fitness Club login credentials is, \n\nUsername : {t_username}, \n\npassword : {t_password}"
         email_from = settings.EMAIL_HOST_USER
         email_to = [t_mail]
         send_mail(subject, message, email_from, email_to)

         register.save()
         print("saved")
         msg = "Trainee Registration Successfull"
         return render(request,"gym_admin/traineeregistration.html", {"msg":msg})

    return render(request,'gym_admin/traineeregistration.html/',{"msg":msg})

def plann(request):
    msg = ''
    if request.method == 'POST':
     p_name = request.POST['planname']
     p_description = request.POST['plandescription']
     p_validity = request.POST['planvalidity']
     p_amount = request.POST['planamount']
     w_type = request.POST['workouttype']
     day_week = request.POST['daysperweek']
     time_workout = request.POST['timeperworkout']
     equip_required = request.POST['equipmentrequired']
     t_gender = request.POST['targetgender']


     user_exist = CreatePlan.objects.filter(plan_name=p_name, plan_validity=p_validity)

     if user_exist:
         msg = "Plan already exist"
     else:
        register = CreatePlan(plan_name = p_name, plan_description = p_description, plan_validity = p_validity, plan_amount = p_amount, workout_type=w_type, days_per_week=day_week, time_per_workout=time_workout, equipment_required=equip_required, target_gender=t_gender)
        register.save()
        print('saved')
        return redirect('gym_admin:plann')

    return render(request,'gym_admin/plann.html/')
def viewalluserregistration(request, id):
    user = Register.objects.get(id=id)

    return render(request,'gym_admin/viewalluserregistration.html/',{"user":user})
def viewregister(request):

    query = Register.objects.all()

    return render(request,'gym_admin/viewregister.html/', {"query":query})

def viewcreatedplan(request):
    ad_viewplan = CreatePlan.objects.all()

    return render(request,'gym_admin/viewcreatedplan.html/', {"ad_viewplan": ad_viewplan})
def addclass(request):
    return render(request,'addclass.html/')
def addworkoutsummary(request):
   
    return render(request,'addworkoutsummary.html/')

def addmachinery(request):
    msg='msg'
    if request.method == 'POST':
        m_name = request.POST['machineryname']
        m_functions = request.POST['machineryfunction']
        m_image = request.FILES['machineryimg']
        m_image=m_image

        
        machinery_exist = AddMachineryDetails.objects.filter(machinery_name=m_name)
        if machinery_exist:
            msg='machinery already exist'
        else:
            register = AddMachineryDetails(machinery_name=m_name, machinery_function=m_functions, machinery_image=m_image)
            register.save()
            return redirect('gym_admin:addmachinery')
        
    return render(request,'gym_admin/addmachinery.html/',{"msg":msg})

def viewfeedback(request):
    v_feedback = EnterFeedback.objects.all()
    return render(request,'gym_admin/viewfeedback.html', {"v_feedback":v_feedback})
def viewtrainee(request):
    traineeview = TraineeRegister.objects.all()
    return render(request,'gym_admin/viewtrainee.html/', {'traineeview':traineeview})
def traineeviewall(request):
    return render(request,'traineeviewall.html/')
def addhealthstatus(request):
    return render(request,'addhealthstatus.html/')
def viewallcreatedplans(request, id):
    view_createdplans = CreatePlan.objects.get(id=id)
    return render(request,'viewallcreatedplans.html/', {"view_createdplans":view_createdplans})
def adminviewmachinery(request):
    admin_view = AddMachineryDetails.objects.all()
    return render(request,'gym_admin/adminviewmachinery.html/', {"admin_view":admin_view})

gym_admin/templates/gym_admin/addhealthstatus.html
{% extends 'adminbase.html'%}

{% block body %}

<body class="">
  <section class="h-100">
    <form action="" name="registerform" method="POST" onsubmit="">
      {% csrf_token %}
      <div class="container py-5 h-30">
        <div class="row d-flex justify-content-center align-items-center h-30">
          <div class="col">
            <div class="card  mx-auto card-registration my-2 card w-100">


              <div class="card-body p-md-8 text-light bg-black">
               <div class="row  mt-0" ><h4 class="mb-5 text-uppercase text-center ">HEALTH STATUS</h4></div>

               <div class="row">
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <label class="form-label text-light" for="form3">First Name</label>
                    <input type="text" name="regname1" id="form3"  class="form-control form-control-sm  bg-dark" placeholder="First Name"/>
                  </div>
                </div>
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <label class="form-label text-light" for="form3Example1n">Last Name</label>
                    <input type="text"  name= "regname2" id="form4" class="form-control form-control-sm bg-dark" placeholder="Last Name" />
                   
                  </div>
                </div>
              </div>


                
                <div class="form-outline mb-2">
                  <label class="form-label text-light" for="form8">Gender</label>
                  <input type="text" name="regpin"  id="form8" class="form-control form-control-sm bg-dark  text-light" placeholder="" maxlength="6" disabled />
                  
                </div>


                <div class="form-outline mb-2">
                  <label class="form-label text-light" for="form8">Blood Group</label>
                  <input type="text" name="regpin"  id="form8" class="form-control form-control-sm bg-dark  text-light" placeholder="" maxlength="6" />
                  
                </div>
                <div class="form-outline mb-2">
                  <label class="form-label text-light" for="form8">Height</label>
                  <input type="text" name="regpin"  id="form8" class="form-control form-control-sm bg-dark text-light" placeholder="" maxlength="6" />
                  
                </div>
                <div class="form-outline mb-2">
                  <label class="form-label text-light" for="form8">Weight</label>
                  <input type="text" name="regpin"  id="form8" class="form-control form-control-sm bg-dark text-light" placeholder="" maxlength="6" />
                  
                  <div class="form-outline mb-2">
                    <label class="form-label text-light" for="form3Example8">Health Status</label>
                    <input type="text" name="regaddress" id="form7" class="form-control form-control-sm bg-dark" placeholder="" />
                    
                  </div>

                
                <div class="d-flex justify-content-between pt-3">
                  <button type="reset" class="btn btn-light btn-sm w-50">Reset all</button>
                  <button type="submit" class="btn btn-warning btn-sm ms-2 w-50">Update</button>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </section>
</body>






{% endblock %}

gym_admin/templates/gym_admin/addmachinery.html
{% extends 'gym_admin/adminbase.html' %}
{% load static %}

{% block head %}
<!--Font Awesome CDN-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<!--Google Font-->
<link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
<!--Stylesheet-->
<link href="{% static 'css/style.css'%}" rel="stylesheet" />
<link href="{% static 'css/addmachine.css'%}" rel="stylesheet" />
{% endblock %}
{% block body %}
<!-- <div class="container"> -->
<section class="h-auto mx-auto w-50">
        <div class="card rounded-3 bg-white">

          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2 text-wrap" style="border-radius: 10px;">Add Machineries</h3>

            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
             
              <div class="row d-flex justify-content-center pt-2 pb-2">
                <div class="col-sm-2 d-flex justify-content-center pb-1">
                  <label> NAME</label>
                </div>
                <div class="col-sm-10 d-flex justify-content-center">
                  <input type="text" name="machineryname" class="inputstyle">
                </div>
              </div>
              <div class="row d-flex justify-content-center pt-2 pb-2">
                <div class="col-sm-2 d-flex justify-content-center">
                  <label for="">FUNCTION</label>

                </div>
                <div class="col-sm-10 d-flex justify-content-center">
                  <textarea class="inputstyle" rows="3" name="machineryfunction"></textarea>
                </div>
              </div>
              <div class="row d-flex justify-content-center pt-3">

                <figure class="image-container">
                  <img id="chosen-image" src="{%static 'assets/img/R.png'%}">
                  <figcaption id="file-name"></figcaption>
                </figure>

                <input type="file" id="upload-button" accept="image/*" name="machineryimg">
                <label for="upload-button" class="labelimg">
                  <i class="fas fa-upload"></i> &nbsp; Choose A Photo
                </label>
              </div>
              <div class="row pt-4">
                <div class="col">
              
              <button type="reset" class="btn btn-light btn-lg btn-block mb-1" >Reset</button>
                </div>
                <div class="col">
              <button type="submit" class="btn btn-light btn-lg btn-block mb-1" >Submit</button>
              </div>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- </div> -->


{% endblock %}

gym_admin/templates/gym_admin/addworkoutsummary.html
{% load static%}
<link rel="stylesheet" href="{% static 'css/workoutsummary.css' %}">


<form>
  <div class="container bg-light">

    <div class="p-2">
    
      <div class="row">
        <div class="col-md-4 p-0 d-flex align-items-center ">
        <label for="text1" class=" text-dark ">Plan name</label>
      </div>
      <div class="col-md-8 ps-0">
        <input type="text" class="form-control" name="workplanname">
      </div>
      </div>

    
      <div class="row ">
        <div class="col-md-4 p-0 d-flex align-items-center">
          <label for="text2" class=" text-dark">Program duration</label>
        </div>
        <div class="col-md-8 ps-0">
          <input type="text" class="form-control" name="programduration">
        </div>
      </div>
      <div class="row ">
        <div class="col-md-4 p-0 d-flex align-items-center">
          <label for="text3" class=" text-dark">Workout type</label>
        </div>
        <div class="col-md-8 ps-0">
          <input type="text" class="form-control" name="workouttype">
        </div>
      </div>
      <div class="row ">
        <div class="col-md-4 p-0 d-flex align-items-center">
          <label for="text4" class=" text-dark">Days per week</label>
        </div>
        <div class="col-md-8 ps-0">
          <input type="text" class="form-control" name="daysperweek">
        </div>
      </div>
      <div class="row ">
        <div class="col-md-4 p-0 d-flex align-items-center">
          <label for="text5" class=" text-dark">Time per workout</label>
        </div>
        <div class="col-md-8 ps-0">
          <input type="text" class="form-control" name="timeperworkout">
        </div>
      </div>
      <div class="row ">
        <div class="col-md-4 p-0 d-flex align-items-center">
          <label for="text2" class=" text-dark">Equipment required</label>
        </div>
        <div class="col-md-8 ps-0">
          <input type="text" class="form-control" name="Equipmentrequired">
        </div>
      </div>
      <div class="row ">
        <div class="col-md-4 p-0 d-flex align-items-center">
          <label for="text2" class=" text-dark">Target gender</label>
        </div>
        <div class="col-md-8 ps-0">
          <div class="form-check form-check-inline  mb-0 me-2">
          <label class="form-check-label form-check-inline">Female</label>
          <input type="radio" class="form-check-input" name="targetgender">
      </div>
        <div class="form-check form-check-inline  mb-0 me-2">
        <label class="form-check-label form-check-inline">Male</label>
        <input type="radio" class="form-check-input" name="targetgender">
      </div>

      <div class="form-check form-check-inline  mb-0 me-2">
        <label class="form-check-label form-check-inline">Both</label>
        <input type="radio" class="form-check-input" name="targetgender">
      </div>

    </div>
    
  
      </div>
      
      <div class="row justify-content-between">
        <div class="col justify-content-between">
          <button type="submit" class="btn btn-warning btn-sm">ADD</button>
        </div>
        <div class="col justify-content-between">
          <button type="reset" class="btn btn-warning btn-sm">RESET</button>
        </div>
      </div>

    </div>
  </div>
</form>


{% endblock %}

gym_admin/templates/gym_admin/adminbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block head %}
    {% endblock %}


    <title>GYM Admin</title>


    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/vewplan.css'%}" rel="stylesheet" />
    <link href="{% static 'css/styles.css'%}" rel="stylesheet" />


    <link href="{% static 'css/registration.css'%}" rel="stylesheet" />
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">


</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav  sidebar sidebar-dark accordion" id="accordionSidebar" style="background-color: #2e2759;">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center"
                href="{% url 'gym_admin:adminhome' %}">
                <div class="sidebar-brand-icon">
                    <!-- <i class="fas fa-laugh-wink"></i> --><img src="{%static 'assets/img/culogo3.png'%}" width="50" height="50" class="d-inline-block align-top " alt="">
                </div>
                <div class="sidebar-brand-text mx-3">Gym Admin</div>

            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'gym_admin:adminhome' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-user"></i>
                    <span>TRAINEE</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <!-- <h6 class="collapse-header">Custom Components:</h6> -->
                        <a class="collapse-item" href="{% url 'gym_admin:traineeregistration' %}">Register</a>
                        <a class="collapse-item" href="{% url 'gym_admin:viewtrainee' %}">View trainee Details</a>
                    </div>
                </div>
            </li>



            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUser"
                    aria-expanded="true" aria-controls="collapseUser">
                    <i class="fas fa-solid fa-user"></i>
                    <span>USER</span>
                </a>
                <div id="collapseUser" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <!-- <h6 class="collapse-header">Custom Components:</h6> -->
                        <a class="collapse-item" href="{% url 'gym_admin:viewregister' %}">View MemberList</a>
                        <a class="collapse-item" href="{% url 'gym_admin:viewfeedback' %}">View feedback</a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePlan"
                    aria-expanded="true" aria-controls="collapsePlan">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Manage Membership Plan</span>
                </a>
                <div id="collapsePlan" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <!-- <h6 class="collapse-header">Custom Components:</h6> -->
                        <a class="collapse-item" href="{% url 'gym_admin:plann' %}">Add Membership Plan</a>
                        <a class="collapse-item" href="{% url 'gym_admin:viewcreatedplan' %}">View Membership Plan</a>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMachinery"
                    aria-expanded="true" aria-controls="collapseMachinery">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Manage Machinery</span>
                </a>
                <div id="collapseMachinery" class="collapse" aria-labelledby="headingTwo"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <!-- <h6 class="collapse-header">Custom Components:</h6> -->
                        <a class="collapse-item" href="{% url 'gym_admin:addmachinery' %}">Add Machinery Details</a>
                        <a class="collapse-item" href="{% url 'gym_admin:adminviewmachinery' %}">View Machinery
                            Details</a>
                    </div>
                </div>
            </li>
           







            <!--  <hr class="sidebar-divider">


            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gym_admin:plann' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Add MembershipPlan</span></a>
            </li>-->

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>


        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>


                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               
                                <span class="mr-2 d-none d-lg-inline text-white small "><button class="btn btn-primary">LOGOUT</button>LOGOUT</span>
                                
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">

                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    {% block body %} {% endblock %}
                </div>
            </div>

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class=" my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
    <!--Script-->
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

gym_admin/templates/gym_admin/viewcreatedplan.html
{% extends 'gym_admin/adminbase.html'%}
{% block body%}



<div class=" vh-100 attendance">
  <div class="container pt-5">
    <div class="card  mx-auto card-registration my-2 card w-auto">


      <div class="card-body p-md-8 text-black bg-white">
        <h2 class="text-uppercase text-center fw-bold text-dark report_font pb-4 ">Membership Plan list</h2>

     
<table class="table">
    <thead>
      <tr class="">
        <th scope="col">#</th>
        <th scope="col"> PLAN NAME</th>
        <th scope="col">DESCRIPTION</th>
        <th scope="col">VALIDITY</th>
        <th scope="col">AMOUNT</th>
        <th scope="col">ACTION</th>
        
      </tr>
    </thead>
    <tbody>
        {% for data in ad_viewplan%}
      <tr class="">
        
        <th scope="row">{{forloop.counter}}</th>
        
        <td>{{data.plan_name}}</td>
        <td>{{data.plan_description}}</td>
        <td>{{data.plan_validity}}</td>
        <td>{{data.plan_amount}}</td>
        <td><a class="btn btn-warning" href="{% url 'gym_admin:viewallcreatedplans' data.id %}">ViewAll</a></td>

        

        
        
      </tr>
      {% endfor%}
      
      
    </tbody>
  </table>
      </div>
    </div>
  </div>
</div>

  
{% endblock %}